language: bash

before_intall:
  - sudo apt-get update && sudo apt-get install -y shellcheck
script:
  - ls -l
  - uname -a
  - ip a
  - bash test.sh
  - pwd
  - cat file
notifications:
  email:
    on_success: never

